name = "ecom-payload-starter"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "ecom-payload-db"
database_id = "26125be3-951c-4d8a-8118-ccbcdbec1edf"