name = "ecom-payload-starter"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# [build]
# command = "pnpm run build"

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "ecom-payload-db"
database_id = "26125be3-951c-4d8a-8118-ccbcdbec1edf"

# Environment variables (will be set via wrangler secret)
# PAYLOAD_SECRET
# RESEND_API_KEY
# RESEND_FROM_EMAIL
# R2_BUCKET
# R2_ACCESS_KEY_ID
# R2_SECRET_ACCESS_KEY
# R2_ENDPOINT