name = "ecom-payload-starter"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[build]
command = "pnpm run build"

[vars]
DATABASE_URI = "libsql://ecom-payload-starter-mohansky.aws-ap-south-1.turso.io"